### ISSUE TITLE
Homework Feedback - HTML/CSS - Week 2

### ISSUE THREAD

**Issue by susaneme** [Mekdes1/hyf-homework#2]
Hi Mekdes :)

- Good job! Your site looks very similar to the of the exercise 👍 !
- I liked that you are using semantic tags, like header, article... which is great 😺 ! 
- I can clearly see your site responsiveness as well the use of media queries in your stylesheet, excellent that you got that! 👏 🥇 
- The image used as site banner is not acting that much responsive, but is just a matter of reviewing your media queries , just some subtle adjustments would make that work
- In terms of enhancements to the current development, you could definitely reduce some classes and containers from your code, a let it more lean and manageable. For example: 
- In `<header><div class='head1'> <h2 class='title'> ....` you could take out the entire div also the class from the `h2` , as you only have one header in your entire document/ page you  could simply refer to the tag and its child in your css, so you could be less specific here if you want. The same applies for the `nav` bar, where you have a `<div class='navbar'>` right underneath, your nav is already specific by the tag iteself, taking out these unecessary `divs` and classes, your code would more lean.
- In your `<div class='details2'>` you added a specific class for each paragraph `<p class='phar'>` yo u dont need that , you simply refer to the tag 🙃 
- Classes are nice and helpful to use, but is also best practice to evaluate if it is really necessary to use, because as more as we use classes, more complex is the code and its maintenance.

You did a excellent job! I can see your applied some concepts presented in the class 👏 🥇 

Well done! 🌷

**Comment by Mekdes1** [comment]
Hi Susane,
Thank you for the feedback,i will implement your comments.

**Comment by senner008** [comment]
Hi :)
Great homework!
Try and look at the comments and see if they make sense. 
Ask if in doubt about anything,
Keep up the great work!
